export const ITEMS = [
  {
    displayedClassName: "AccountRequisitesPersonsRub",
    currency: "RUR",
    bankInn: "4455332215",
    bankKpp: "12377777",
    bankName: "Бис Банк1",
    bankBic: "000000001",
    bankCorrespondentAccount: "30102810000000161456",
    bankCorrespondentName: "",
    bankCorrespondentSwift: "",
    bankBeneficiaryName: "BIS BANK, MOSCOW",
    bankBeneficiarySwift: "BICBANKMAXX",
    clientInn: "test",
    clientKpp: "test",
    forRubAccounts: false,
    clientCategory: "Persons"
  },
  {
    displayedClassName: "AccountRequisitesPersonsCurrency",
    currency: "USD",
    bankInn: "",
    bankKpp: "",
    bankName: "",
    bankBic: "",
    bankCorrespondentAccount: "",
    bankCorrespondentName: "CITI BANK N.A.",
    bankCorrespondentSwift: "CITIUS33XXX",
    bankBeneficiaryName: "BIS BANK, MOSCOW",
    bankBeneficiarySwift: "BISBANKMAXX",
    clientInn: null,
    clientKpp: null,
    forRubAccounts: false,
    clientCategory: "Persons"
  },
  {
    displayedClassName: "AccountRequisitesPersonsCurrencyToRub",
    currency: "EUR",
    bankInn: "",
    bankKpp: "",
    bankName: "",
    bankBic: "",
    bankCorrespondentAccount: "",
    bankCorrespondentName: "DEUTESCHE BANK AG",
    bankCorrespondentSwift: "DEUTDE1HXXX",
    bankBeneficiaryName: "BIS BANK, MOSCOW",
    bankBeneficiarySwift: "BISBANKMAXX",
    clientCategory: "Persons",
    forRubAccounts: true
  },
  {
    displayedClassName: "AccountRequisitesPersonsCurrency",
    currency: "EUR",
    bankInn: "",
    bankKpp: "",
    bankName: "",
    bankBic: "",
    bankCorrespondentAccount: "",
    bankCorrespondentName: "DEUTESCHE BANK AG",
    bankCorrespondentSwift: "DEUTDE1HXXX",
    bankBeneficiaryName: "BIS BANK, MOSCOW",
    bankBeneficiarySwift: "BISBANKMAXX",
    forRubAccounts: false,
    clientInn: "testcurrency",
    clientKpp: "testcurrency",
    clientCategory: "Persons"
  },
  {
    displayedClassName: "AccountRequisitesPersonsCurrencyToRub",
    currency: "USD",
    bankInn: "",
    bankKpp: "",
    bankName: "",
    bankBic: "",
    bankCorrespondentAccount: "",
    bankCorrespondentName: "CITI BANK N.A.",
    bankCorrespondentSwift: "CITIUS33XXX",
    bankBeneficiaryName: "BIS BANK, MOSCOW",
    bankBeneficiarySwift: "BICBANKMAXX",
    forRubAccounts: true,
    clientInn: "testcurrencytorub",
    clientKpp: "testcurrencytorub",
    clientCategory: "Persons"
  },
  {
    displayedClassName: "AccountRequisitesOrganizationsRub",
    bankBeneficiaryName: "BIS BANK, MOSCOW",
    bankBeneficiarySwift: "BICBANKMAXX",
    bankBic: "000000001",
    bankCorrespondentAccount: "30102810000000161456",
    bankCorrespondentName: "",
    bankCorrespondentSwift: "",
    bankInn: "4455332215",
    bankKpp: "12377777",
    bankName: "Бис Банк1",
    clientCategory: "Organizations",
    clientInn: "organizationstest",
    clientKpp: "organizationstest",
    currency: "RUR",
    forRubAccounts: false
  },
  {
    displayedClassName: "AccountRequisitesOrganizationsCurrency",
    bankBeneficiaryName: "BIS BANK, MOSCOW",
    bankBeneficiarySwift: "BISBANKMAXX",
    bankBic: "000000001",
    bankCorrespondentAccount: "30102810000000161456",
    bankCorrespondentName: "CITI BANK N.A.",
    bankCorrespondentSwift: "CITIUS33XXX",
    bankInn: "4455332215",
    bankKpp: "12377777",
    bankName: "Бис Банка1",
    clientCategory: "Organizations",
    clientInn: "organizationstestcurrency",
    clientKpp: "organizationstestcurrency",
    currency: "EUR",
    forRubAccounts: false
  },
  {
    displayedClassName: "AccountRequisitesOrganizationsCurrencyToRub",
    bankBeneficiaryName: " BIS BANK, MOSCOW",
    bankBeneficiarySwift: "BICBANKMAXX",
    bankBic: "000000002",
    bankCorrespondentAccount: "30102810000000161457",
    bankCorrespondentName: "DEUTESCHE BANK AG",
    bankCorrespondentSwift: "DEUTDE1HXXX",
    bankInn: "44553332215",
    bankKpp: "12377777",
    bankName: "Бис Банк1",
    clientCategory: "Organizations",
    clientInn: "organizationstestcurrencytorub",
    clientKpp: "organizationstestcurrencytorub",
    currency: "USD",
    forRubAccounts: true
  },
  {
    displayedClassName: "AccountRequisitesOrganizationsCurrency",
    currency: "USD",
    bankInn: "",
    bankKpp: "",
    bankName: "",
    bankBic: "",
    bankCorrespondentAccount: "",
    bankCorrespondentName: "CITI BANK N.A.",
    bankCorrespondentSwift: "CITIUS33XXX",
    bankBeneficiaryName: "BIS BANK, MOSCOW",
    bankBeneficiarySwift: "BISBANKMAXX",
    forRubAccounts: false,
    clientCategory: "Organizations"
  }
];
